version: "3.9"

services:
  library:
    build: ./library
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app-data
    depends_on:
      - counter

  counter:
    build: ./counter
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./data:/app-data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo