version: "3.9"

services:
  library:
    build: ./library
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app-data
    depends_on:
      - counter

  counter:
    build: ./counter
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./data:/app-data
